### ISSUE TITLE
建议RtmpPlaySdk.dll去除对 MSVCR100.DLL的依赖

### ISSUE THREAD

**Issue by rmbgold** [waterfoxfox/RtmpPlayer#1]
1.建议RtmpPlaySdk.dll去除对 MSVCR100.DLL的依赖
2.AVClient.exe在播放过程中如果最小化窗口到任务栏，再恢复窗口后，窗口无画面内容。日志显示
[2020-09-21 00:17:29.307] [23584] [LOG_WARN] CAudioDecoder::decode, Error while decoding frame! [SDAudioDecoder.cpp:145] [0]
3.推流端编码率设置为2048KB/S的时候，AVClient.exe经常会画面卡住，日志报上面相同的警告。推流端编码率设置为1024KB/S的时候则不会出现这种情况。

**Comment by rmbgold** [comment]
测试操作系统为win10家庭版，推流工具为
https://github.com/tsingsee/EasyScreenLive
Win32版本。

**Comment by waterfoxfox** [comment]
1、最小化无画面显示是DEMO上一次修改引入的bug，与DLL无关，已修复。   2、高码率16Mbps的情况下，IDR帧码流很大，存在超出模块预期值（960*540字节）而内部主动丢弃该帧的情况，现增加单帧码流允许的字节数为1280*720字节后解决。
