### ISSUE TITLE
声音延迟

### ISSUE THREAD

**Issue by ToJane** [waterfoxfox/RtmpPlayer#2]
在播放几十秒后,声音和画面遇到了几秒延迟
播放类型:RTMP

**Comment by waterfoxfox** [comment]
方便的话，可以把日志文件发我   QQ 1821554146

**Comment by ToJane** [comment]
[EDV8737_Debug_202011250919_014072_000.log](https://github.com/waterfoxfox/RtmpPlayer/files/5593781/EDV8737_Debug_202011250919_014072_000.log)

**Comment by waterfoxfox** [comment]
> 在播放几十秒后,声音和画面遇到了几秒延迟
> 播放类型:RTMP

请问，你设置的缓存时间是不是非常小，且不为0，设置的多少

**Comment by waterfoxfox** [comment]
> > 在播放几十秒后,声音和画面遇到了几秒延迟
> > 播放类型:RTMP
> 
> 请问，你设置的缓存时间是不是非常小，且不为0，设置的多少

新版已经修复这个缺陷，避免外层设置的JitterBuff时间过小（小于两个数据包时间间隔）
