### ISSUE TITLE
音视频不同步

### ISSUE THREAD

**Issue by bishangshuo** [waterfoxfox/RtmpPlayer#3]

**Comment by waterfoxfox** [comment]
能提供设置的缓存大小值？如果方便可以私下提供下播放地址？不同步的程度大概怎样，由于没有做播放时唇音同步，所以可能有细微的不同步。

**Comment by waterfoxfox** [comment]
音频缓存较大导致网络较差且使用0延时配置时，累积了较多数据才被重新置位
